### ISSUE TITLE
Migrating into an already existing project with environments that differ from the source project will break the script

### ISSUE THREAD

**Issue by durw4rd** [launchdarkly-labs/project-migrator-script#5]
If one creates the target project manually while not making sure the new project's environment configuration matches exactly the situation in the old/source project, the script will fail with 400 errors.
![image](https://user-images.githubusercontent.com/17836183/195812510-3e19fdf8-301b-412b-b6dd-40f622663a92.png)

A low-effort fix would be calling out in the README file that one should not be creating the target project manually but instead leave this for the script.

**Comment by cgreenld** [comment]
Hey, we want to avoid the "merge project scenario" if you want to take a look at my solutions I added a PR here: https://github.com/launchdarkly-labs/project-migrator-script/pull/7
